routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

/**
 * ==================================
 * Backoffice routes...
 * ==================================
 */

/**
 * Request routes...
 */
Route::get('pemohon', 'Backoffice\RequestController@index')->name('request.index');
Route::get('pemohon/{id}/show', 'Backoffice\RequestController@show')->name('request.show');
Route::get('pemohon/{id}/delete', 'Backoffice\RequestController@delete')->name('request.delete');
Route::delete('pemohon/{id}/destroy', 'Backoffice\RequestController@destroy')->name('request.destroy');

/**
 * Violation routes...
 */
Route::get('pelanggaran', 'Backoffice\ViolationController@index')->name('violation.index');

/**
 * ==================================
 * Public routes...
 * ==================================
 */
Route::get('daftar', 'RequestController@create')->name('register.create');
Route::post('daftar', 'RequestController@store')->name('register.store');

app/Request.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class Request extends Model implements HasMedia
{
    use HasMediaTrait;

    protected $casts = [
        'is_active' => 'boolean'
    ];

    protected $dates = [
        'active_from',
        'active_to'
    ];

    protected $fillable = [
        'nik',
        'nama',
        'tempat_lahir',
        'tgl_lahir',
        'agama',
        'pekerjaan',
        'alamat_sekarang',
        'jk',
    ];

    /**
     * Jenis kelamin mutator.
     *
     * @return string
     */
    public function getGenderAttribute()
    {
        if ($this->jk === 'l') {
            return 'Laki-laki';
        } elseif ($this->jk === 'p') {
            return 'Perempuan';
        } else {
            return '';
        }
    }

    /**
     * Cek status aktif.
     *
     * @return bool
     */
    public function isActive()
    {
        return $this->is_active;
    }

    /**
     * Cek status kadaluarsa.
     *
     * @return bool
     */
    public function isExpired()
    {
        if ($this->isActive()) {
            return $this->active_to < date('Y-m-d');
        }
    }

    /**
     * Status mutator.
     *
     * @return string
     */
    public function getStatusAttribute()
    {
        return $this->isActive() ? 'Aktif' : 'Tidak aktif';
    }

    /**
     * Format Tanggal lahir mutator.
     *
     * @return false|string
     */
    public function getBirthDayAttribute()
    {
        return date_format(date_create($this->tgl_lahir), 'd-M-Y');
    }

    /**
     * Agama Mutator.
     *
     * @return string
     */
    public function getReligionAttribute()
    {
        return ucfirst($this->agama);
    }

    /**
     * Tanggal Aktif Mutator.
     *
     * @return false|string
     */
    public function getActiveDateAttribute()
    {
        return date_format(date_create($this->active_from), 'd-M-Y');
    }

    /**
     * Tanggal Kadaluarsa Mutator.
     *
     * @return false|string
     */
    public function getExpireDateAttribute()
    {
        return date_format(date_create($this->active_to), 'd-M-Y');
    }

    /**
     * ID Registrasi mutator.
     *
     * @return string
     */
    public function getIdRegAttribute()
    {
        return strtoupper($this->reg_id);
    }

    public function violation()
    {
        return $this->hasMany(Violation::class, 'nik', 'nik');
    }
}

app/Http/Controllers/Backoffice/RequestController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Http\Controllers\Controller;
use App\Request;

class RequestController extends Controller
{
    /**
     * RequestController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $requests = Request::latest()->paginate(10);

        return view('backoffice.requests.index', compact('requests'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $request = Request::with('violation')->findOrFail($id);

        return view('backoffice.requests.show', compact('request'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Show the delete confirmation form view.
     *
     * @param $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function delete($id)
    {
        $request = Request::findOrFail($id);

        return view('backoffice.requests.delete', compact('request'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Request::find($id)->delete();

        return redirect()->route('request.index');
    }
}

app/Http/Controllers/Backoffice/ViolationController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Violation;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ViolationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $violations = Violation::with('people')->latest()->paginate(15);

        return view('backoffice.violations.index', compact('violations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/RequestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class RequestController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('requests.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return request()->all();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backoffice/requests/delete.blade.php
@extends('layouts.app')

@section('title')
    Konfirmasi Hapus Pemohon {{ $request->nama }} - {{ $request->nik }}
@endsection

@section('content')
    <form action="{{ route('request.destroy', $request->id) }}" method="POST">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
        <h4>Apakah anda yakin ingin menghapus data pemohon ini?</h4>
        <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Hapus</button>
        <a href="{{ route('request.index') }}" class="btn btn-default">Batal</a>
    </form>
@endsection

resources/views/backoffice/requests/index.blade.php
@extends('layouts.app')

@section('title')
    Pemohon
@endsection

@section('content')
    <form action="">
        <input type="text" name="search" id="search" class="form-control" placeholder="Cari...">
    </form>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>#ID</th>
            <th>NIK</th>
            <th>Nama</th>
            <th>Jenis Kelamin</th>
            <th>
                Tindakan
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach($requests as $request)
            <tr class="@if($request->isActive()) success @endif @if($request->isExpired()) danger @endif">
                <td>{{ $request->id }}</td>
                <td>{{ $request->nik }}</td>
                <td>{{ $request->nama }}</td>
                <td>{{ $request->gender }}</td>
                <td>
                    <div class="btn-group btn-group-xs" role="group">
                        <a href="{{ route('request.show', $request->id) }}" class="btn btn-default" title="Lihat"><i class="glyphicon glyphicon-zoom-in"></i></a>
                        <button type="button" class="btn btn-default" title="Edit"><i class="glyphicon glyphicon-edit"></i></button>
                        <a href="{{ route('request.delete', $request->id) }}" class="btn btn-danger" title="Hapus"><i class="glyphicon glyphicon-trash"></i></a>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {!! $requests->links() !!}
@endsection

resources/views/backoffice/requests/show.blade.php
@extends('layouts.app')

@section('title')
    {{ $request->nama }} - {{ $request->nik }}
@endsection

@section('content')
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <caption><b>Biodata</b></caption>
                <tr>
                    <td>#ID</td>
                    <td width="1%">:</td>
                    <td>{{ $request->id }}</td>
                </tr>
                <tr>
                    <td>NIK</td>
                    <td width="1%">:</td>
                    <td>{{ $request->nik }}</td>
                </tr>
                <tr>
                    <td>Nama</td>
                    <td width="1%">:</td>
                    <td>{{ $request->nama }}</td>
                </tr>
                <tr>
                    <td>Jenis Kelamin</td>
                    <td width="1%">:</td>
                    <td>{{ $request->gender }}</td>
                </tr>
                <tr>
                    <td>Tempat Lahir</td>
                    <td width="1%">:</td>
                    <td>{{ $request->tempat_lahir }}</td>
                </tr>
                <tr>
                    <td>Tanggal Lahir</td>
                    <td width="1%">:</td>
                    <td>{{ $request->birthday }}</td>
                </tr>
                <tr>
                    <td>Agama</td>
                    <td width="1%">:</td>
                    <td>{{ $request->religion }}</td>
                </tr>
                <tr>
                    <td>Pekerjaan</td>
                    <td width="1%">:</td>
                    <td>{{ $request->pekerjaan }}</td>
                </tr>
                <tr>
                    <td>Alamat Sekarang</td>
                    <td width="1%">:</td>
                    <td>{{ $request->alamat_sekarang }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table">
                <caption><b>Status</b></caption>
                <tr>
                    <td>Status</td>
                    <td width="1%">:</td>
                    <td>
                        @if($request->isExpired())
                            <span class="label label-danger">Kadaluarsa</span>
                        @else
                            <span class="label @if($request->isActive()) label-success @else label-default @endif">{{ $request->status }}</span>
                        @endif
                    </td>
                </tr>
                @if($request->isActive())
                    <tr>
                        <td>Nomor Registrasi</td>
                        <td width="1%">:</td>
                        <td>{{ $request->idReg }}</td>
                    </tr>
                    <tr>
                        <td>Tanggal Aktif</td>
                        <td width="1%">:</td>
                        <td>{{ $request->activeDate }}</td>
                    </tr>
                    <tr>
                        <td>Tanggal Kadaluarsa</td>
                        <td width="1%">:</td>
                        <td>{{ $request->expireDate }}</td>
                    </tr>
                @endif
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <caption><b>Pelanggaran</b></caption>
                <thead>
                <tr>
                    <th>Tanggal</th>
                    <th>Deskripsi</th>
                </tr>
                </thead>
                <tbody>
                @forelse($request->violation as $violation)
                    <tr>
                        <td>{{ $violation->date }}</td>
                        <td>{{ $violation->keterangan }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="2">Belum ada data.</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection